const actionTypes = {
    FETCH_PARTICIPANT_LIST: 'FETCH_PARTICIPANT_LIST',
    GET_PARTICIPANT_LIST_SUCCESS: 'GET_PARTICIPANT_LIST_SUCCESS',
    SET_SELECTED_PARTICIPANT: 'SET_SELECTED_PARTICIPANT',
    REMOVE_PARTICIPANT_LIST_SUCCESS: 'REMOVE_PARTICIPANT_LIST_SUCCESS'
};

export default actionTypes;
