const actionTypes = {
    SET_SELECTED_PARTICIPANT: 'SET_SELECTED_PARTICIPANT',
    REMOVE_PARTICIPANT_LIST_SUCCESS: 'REMOVE_PARTICIPANT_LIST_SUCCESS',
    UPDATE_PARTICIPANT_LIST: 'UPDATE_PARTICIPANT_LIST',
    UPDATE_PARTICIPANT_LIST_ERROR: 'UPDATE_PARTICIPANT_LIST_ERROR',
};

export default actionTypes;
